[tool.poetry]
name = "calendarsave"
version = "0.1.0"
description = ""
authors = ["Sarah Vogels <114360057+sarahvgls@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ics = "^0.7.2"
pytz = "^2025.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
